FROM node:20-alpine AS build-stage
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build-dev

FROM nginx:1.25.4-alpine-slim AS run-stage
COPY ./nginx-dev.conf /etc/nginx/nginx.conf
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 8088
ENTRYPOINT ["nginx", "-g", "daemon off;"]